create server and router #9
FACK1/Mylibrary pull request #22
Opened 2018-12-11 12:55 UTC by Samaamro20

- create server.js
- create router.js

2018-12-11 13:33 UTC, jema28 requested changes

2018-12-11 13:33 UTC, jema28 commented on src/server/server.js
> +require('dotenv').config()
You're already using env2 in another file: dotenv is the same thing so isn't not necessary to have both.

2018-12-11 13:33 UTC, jema28 commented on src/server/router.js
> + 	// if (pathname === '/' ) {
Please delete these comments if not being used.

2018-12-11 13:33 UTC, jema28 commented on src/server/router.js
> +// const payload = {
Please delete these comments also, they shouldn't be in this pull request.

2018-12-12 09:33 UTC, amanshawar approved these changes

2018-12-12 09:33 UTC, Hadeel-Salamin approved these changes

2018-12-12 10:00 UTC, jema28 requested changes

2018-12-12 10:00 UTC, jema28 commented on src/server/handler.js
> +const SECRET = '123book123';
Secret shouldn't be here!

2018-12-12 10:00 UTC, jema28 commented on src/server/handler.js
> +//const getData=require('./queries/get.js');
Look at the comments and see if you can get rid of them.

2018-12-12 10:00 UTC, jema28 commented on src/server/handler.js
> +		'Set-Cookie': `logged_in=${0}; Max-Age=0`
Why do you need to put 0 in $`` here?

2018-12-12 10:00 UTC, jema28 commented on src/server/handler.js
> +const querystring = require('querystring');
Request and cookie modules aren't being used.

2018-12-12 10:00 UTC, jema28 commented on src/server/handler.js
> +var token = jwt.sign(userDetails, SECRET);
please change var to const or let here to keep things consistent.

2018-12-12 10:09 UTC, jema28 approved these changes

2018-12-12 10:09 UTC, merged